"""
> student_difficulty_evaluator.py

Replaces NeSIG's PlannerEvaluator with a student-based difficulty evaluator.
Instead of measuring difficulty via a planner, difficulty is measured by how
hard it is for the student agent to solve the problem:

    - If the student solves it:  difficulty = num_steps / max_actions  (in [0, 1])
    - If the student fails:      difficulty = penalty (fixed negative value)

This class follows the DifficultyEvaluator interface from NeSIG so it can be
dropped in as a direct replacement inside ProblemGenerator.
"""

import os
import tempfile
import shutil
import torch
from typing import List, Tuple, Union
from pathlib import Path

from src.nesig.metrics.difficulty import DifficultyEvaluator
from src.nesig.symbolic.pddl_problem import PDDLProblem as NeSIGProblem

from src.agent.controller.train_and_test_ACG import load_problems_from_dir


class StudentDifficultyEvaluator(DifficultyEvaluator):
    """
    Evaluates problem difficulty using the student agent's performance.

    Parameters
    ----------
    student_solver : ProblemSolver
        The student's ProblemSolver instance.
    max_actions : int
        Action budget given to the student per problem.
    domain_path : str
        Path to the shared domain PDDL file.
    penalty : float
        Difficulty reward when the student fails. Should be negative (e.g. -1.0).
    """

    def __init__(self, student_solver, max_actions: int, domain_path: str,
                 penalty: float = -1.0):
        self.student_solver = student_solver
        self.max_actions = max_actions
        self.domain_path = domain_path
        self.penalty = penalty

    def get_difficulty(
        self,
        problem_list: List[Union[NeSIGProblem, Path]],
    ) -> Tuple[List[float], List[float]]:
        """
        Evaluate difficulty for a list of NeSIG-generated problems.

        Dumps each NeSIG problem to a temporary PDDL file, loads them with
        the student's parser, solves them, and derives difficulty from the result.

        Parameters
        ----------
        problem_list : List[NeSIGProblem]
            Consistent problems generated by NeSIG's ProblemGenerator.

        Returns
        -------
        difficulties : List[float]
            Raw difficulty value per problem.
        difficulty_rewards : List[float]
            Reward signal passed back to NeSIG's PPO update.
        """
        if not problem_list:
            return [], []

        temp_dir = tempfile.mkdtemp()
        try:
            # Dump NeSIG problems to temp PDDL files
            for i, problem in enumerate(problem_list):
                path = os.path.join(temp_dir, f'problem_{i}.pddl')
                with open(path, 'w') as f:
                    f.write(problem.dump_to_pddl(f'problem_{i}'))

            # Load with student's existing infrastructure
            student_problems = load_problems_from_dir(
                temp_dir,
                self.domain_path,
                len(problem_list),
                max_actions=self.max_actions,
            )

            # Solve with student
            with torch.no_grad():
                _, problem_info_list, _, _ = self.student_solver.solve_problems(
                    student_problems,
                    list_max_actions=self.max_actions,
                )

        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

        # Derive difficulty from student performance
        difficulties = []
        difficulty_rewards = []
        for info in problem_info_list:
            if info['goal_reached']:
                # More steps = harder = higher reward for NeSIG
                diff = info['num_steps'] / self.max_actions
            else:
                diff = self.penalty

            difficulties.append(diff)
            difficulty_rewards.append(diff)

        return difficulties, difficulty_rewards